#+title: coding patterns
* intro
** comparison 
source: https://bytebytego.com/my-courses
|------------------------+---------------------------------+----------------------------------------+-----------------+--------+--------------------------------------------------|
| pattern                | strategy                        | algorithms                             | time            | space  | notes                                            |
|------------------------+---------------------------------+----------------------------------------+-----------------+--------+--------------------------------------------------|
| two pointer            | general                         | nested for loops                       | O(n^2)          | O(1)?  | garbage collection                               |
|                        | inward traversal                | pair sum - sorted                      | O(n)            | O(1)   |                                                  |
|                        |                                 | triplet sum                            | O(n^2)          | O(n)   | sort time O(nlogn); output included space O(n^2) |
|                        |                                 | largest container                      | O(n)            | O(1)   |                                                  |
|                        |                                 | isPalindrom valid                      | O(n)            | O(1)   |                                                  |
|                        | staged traversal                | next lexicographical sequence          | O(n)            | O(n)   |                                                  |
|                        | unidirectional traversal        | shift zeros to end                     | O(n)            | O(1)   |                                                  |
|------------------------+---------------------------------+----------------------------------------+-----------------+--------+--------------------------------------------------|
| hash maps and sets     | hash maps                       | pair sum - unsorted                    | O(n)            | O(n)   |                                                  |
|                        |                                 | geometric seq triplets                 | O(n)            | O(n)   |                                                  |
|                        | hash sets                       | verify sudoku board                    | O(n^2)          | O(n^2) |                                                  |
|                        |                                 | zero striping                          | O(m*n)          | O(1)   |                                                  |
|                        |                                 | longest chain of conseq' #s            | O(n)            | O(n)   | sorted                                           |
|------------------------+---------------------------------+----------------------------------------+-----------------+--------+--------------------------------------------------|
| linked lists           | traversal                       | linked list intersection               | O(n+m)          | O(1)   | music player                                     |
|                        |                                 | palindrom linked list                  |                 |        |                                                  |
|                        | restructuring                   | linked list reversal                   | O(n)            | O(n)   |                                                  |
|                        |                                 | remove the kth last node               | O(n)            | O(1)   |                                                  |
|                        |                                 | flatten a multilevel list              | O(n)            | O(1)   |                                                  |
|                        | doubly linked list              | lru cache                              | O(1)            | O(n)   |                                                  |
|------------------------+---------------------------------+----------------------------------------+-----------------+--------+--------------------------------------------------|
| fast and slow pointers | cycle detection                 | linked list loop                       | O(n)            | O(1)   |                                                  |
|                        | fractional point identification | linked list midpoint                   | O(n)            | O(1)   |                                                  |
|                        | sequence analysis               | happy number                           |                 |        |                                                  |
|------------------------+---------------------------------+----------------------------------------+-----------------+--------+--------------------------------------------------|
| sliding windows        | fixed sliding window            | substring (ss) anagram                 | O(n)            | O(1)   |                                                  |
|                        | dynamic sliding window          | longest ss with uniq char's            | O(n)            | O(m)   |                                                  |
|                        |                                 | longest uniform ss after replcmnt      | O(n)            | O(m)   |                                                  |
|------------------------+---------------------------------+----------------------------------------+-----------------+--------+--------------------------------------------------|
| binary search          | sorted arrays                   | first & last occurences of a #         | O(log(n))       | O(1)   |                                                  |
|                        |                                 | find the insertion index               | O(log(n))       | O(1)   |                                                  |
|                        | partially sorted arrays         | find target in rotated sorted array    | O(log(n))       | O(1)   |                                                  |
|                        | matrix                          | matrix search                          | O(log(m.n))     | O(1)   |                                                  |
|                        | multiple arrays                 | find median from 2 sorted arrays       | O(log(min(m,n)) | O(1)   |                                                  |
|                        | non-intuitive search space      | cutting wood                           | O(nlog(m))      | O(1)   |                                                  |
|                        |                                 | local maxima in array                  | O(log(n))       | O(1)   |                                                  |
|                        |                                 | weighted random selection              | O(log(n))       | O(1)   |                                                  |
|------------------------+---------------------------------+----------------------------------------+-----------------+--------+--------------------------------------------------|
| stacks                 | nested structures               | valid parenthesis expression           | O(n)            | O(1)   |                                                  |
|                        |                                 | evaluate expression                    | O(n)            | O(n)   |                                                  |
|                        | deque                           | maximums of sliding windows            | O(n)            | O(k)   |                                                  |
|                        | processing duplicates           | repeated removal of adj duplicates     | O(1)            | O(n)   |                                                  |
|                        | monotonic stack                 | nxt largest number to the right        | O(n)            | O(n)   |                                                  |
|                        | queue                           | implementation                         | O(1)            | O(n)   |                                                  |
|------------------------+---------------------------------+----------------------------------------+-----------------+--------+--------------------------------------------------|
| heaps                  | sorting                         | combine sorted linked lists            |                 |        |                                                  |
|                        |                                 | sort a k-sorted array                  |                 |        |                                                  |
|                        | finding values in sorted order  | k most frequent strings                |                 |        |                                                  |
|                        |                                 | median of integer stream               |                 |        |                                                  |
|------------------------+---------------------------------+----------------------------------------+-----------------+--------+--------------------------------------------------|
| intervals              | managing overlaps               | merge overlapping intervals            |                 |        |                                                  |
|                        |                                 | identify all interval overlaps         |                 |        |                                                  |
|                        | finding values in sorted order  | largest overlap of intervals           |                 |        |                                                  |
|------------------------+---------------------------------+----------------------------------------+-----------------+--------+--------------------------------------------------|
| prefix sums            | subarray sums                   | sum between range                      |                 |        |                                                  |
|                        |                                 | k-sum subarrays                        |                 |        |                                                  |
|                        | product sums                    | without current element                |                 |        |                                                  |
|------------------------+---------------------------------+----------------------------------------+-----------------+--------+--------------------------------------------------|
| trees                  | depth first search (dfs)        | invert binary tree                     |                 |        |                                                  |
|                        |                                 | balanced binary tree validation        |                 |        |                                                  |
|                        |                                 | binary search tree validation          |                 |        |                                                  |
|                        |                                 | lowest common ancestor                 |                 |        |                                                  |
|                        |                                 | build bt - preorder & inorder tr       |                 |        |                                                  |
|                        |                                 | max sum of continuous path             |                 |        |                                                  |
|                        |                                 | bt symmetry                            |                 |        |                                                  |
|                        |                                 | kth smallest # in bst                  |                 |        |                                                  |
|                        |                                 | serialize and deserialize              |                 |        |                                                  |
|                        | breadth first search (bfs)      | rightmost nodes of a bt                |                 |        |                                                  |
|                        |                                 | widest binary tree level               |                 |        |                                                  |
|                        |                                 | binary tree columns                    |                 |        |                                                  |
|------------------------+---------------------------------+----------------------------------------+-----------------+--------+--------------------------------------------------|
| tries                  | implementation                  | design a trie                          |                 |        |                                                  |
|                        |                                 | insert and search words with wildcards |                 |        |                                                  |
|                        | traversal                       | find all words on a board              |                 |        |                                                  |
|------------------------+---------------------------------+----------------------------------------+-----------------+--------+--------------------------------------------------|
| graphs                 | dfs                             | graph deep copy                        |                 |        |                                                  |
|                        |                                 | count islands                          |                 |        |                                                  |
|                        |                                 | bipartite graph validation             |                 |        |                                                  |
|                        |                                 | longest increasing path                |                 |        |                                                  |
|                        | bfs                             | matrix infection                       |                 |        |                                                  |
|                        |                                 | shortest transformation sequence       |                 |        |                                                  |
|                        | dijiktra's algorithm            | shortest path                          |                 |        |                                                  |
|                        | topological sort                | prerequisites                          |                 |        |                                                  |
|                        | union-find                      | merging communities                    |                 |        |                                                  |
|                        |                                 | connect the dots                       |                 |        |                                                  |
|------------------------+---------------------------------+----------------------------------------+-----------------+--------+--------------------------------------------------|
| backtracking           | permutations                    | find all permutations                  |                 |        |                                                  |
|                        |                                 | n queens                               |                 |        |                                                  |
|                        | combinations                    | combinations of sum                    |                 |        |                                                  |
|                        |                                 | phone keypad combination               |                 |        |                                                  |
|                        | subsets                         | find all subsets                       |                 |        |                                                  |
|------------------------+---------------------------------+----------------------------------------+-----------------+--------+--------------------------------------------------|
| dynamic programming    |                                 |                                        |                 |        |                                                  |
| greedy                 |                                 |                                        |                 |        |                                                  |
| sort and search        |                                 |                                        |                 |        |                                                  |
| bit manipulation       |                                 |                                        |                 |        |                                                  |
| math and geometry      |                                 |                                        |                 |        |                                                  |
|------------------------+---------------------------------+----------------------------------------+-----------------+--------+--------------------------------------------------|
** notes
*** two pointers
- requires a linear data structure, such as an array or linked list
- mostly does not take advantage of predictable dynamics (sorted list)
- most common use case - garbage collection - 'scan' and 'free' pointers used for memory compaction - he goal is to free up contiguous memory space by eliminating gaps left by deallocated (aka dead) objects
*** hash maps and hash sets
- information density and intent
- hash map - a map is a function of its keys
  - associative mapping (key -> value) - lookup -> hash map
  - domain models - entities and relationships -> hash map
- hash set - a set is its own membership predicate
  - existence / membership check and set logic -> hash set
  - categories and filtering -> hash set
*** linked lists
- single linked list
  - head, last node points to null
  - dynamic sizing (array has static size)
  - frequent insertions and deletions 
  - random access not possible 
- double linked list
  - two references: next and prev
  - head node and tail node
  - bidirectional traversal
  - insertion / deletion is easier 
- real world examples: music playlist, 
- linked list reversal
- remove kth last node from a linked list
- linked list intersection
  - an intersection occurs when two linked lists converge at a shared node and, from that point onwards, share all subsequent nodes
  - tortoise and the hare algorithm (floyd’s cycle-finding algorithm) developed by robert w. floyd to detect closed loops
- lru cache
  - cache capacity, return value (-1 if key doesn't exit), add key-value, update key-value, evict least recently used element if cache exceeds capacity 
    combination of data structures: hash map and doubly linked list
- flatten multilevel linked list
  - he order of the nodes on each level needs to be preserved
  - all the nodes in one level must connect before appending nodes from the next level
** fast and slow pointers
- example:
  - detect symlinks which are shortcuts that point to files or directories in a file system
  - find and return midpoint(/s) of a list
  - happy number - a number that, when repeatedly subjected to the process of squaring its digits and summing those squares, eventually leads to 1. an unhappy number will never reach 1 during this process, and will get stuck in an infinite loop 
** sliding windows
- example: buffering in video streaming 
- two pointers - left and right - instead of nested loops 
- terminology
  - to expand the window is to advance the right pointer
  - to shrink the window is to advance the left pointer
  - to slide the window is to advance both the left and right pointer
- fixed sliding window - find a subcomponent of a certain length
  - substring anagram - given two strings, s and t , both consisting of lowercase English letters, return the number of substrings in s that are anagrams of t
- dynamic sliding window - find the longest or shortest subcomponent that satisfies a condition
  - longest substring with unique characters - given a string, determine the length of its longest substring that consists only of unique characters.
  - longest uniform substring after replacements - a uniform substring is one in which all characters are identical. given a string, determine the length of the longest uniform substring that can be formed by replacing up to k characters.
** binary search
- implementation steps:
  - define the search space
  - define the behavior inside the loop for narrowing the search space
  - choose an exit condition for the while-loop
  - return the correct value
- example: transaction search in financial systems
- insertion index - you are given a sorted array that contains unique values, along with an integer target. if the array contains the target value, return its index. otherwise, return the insertion index. this is the index where the target would be if it were inserted in order, maintaining the sorted sequence of the array.
- first and last occurence - given an array of integers sorted in non-decreasing order, return the first and last indexes of a target number. if the target is not found, return [-1, -1]
- cutting wood - you are given an array representing the heights of trees, and an integer k representing the total length of wood that needs to be cut.
- find target in a rotated sorted array - a rotated sorted array is an array of numbers sorted in ascending order, in which a portion of the array is moved from the beginning to the end. given a rotated sorted array of unique numbers, return the index of a target value. if the target value is not present, return -1.
- median from sorted arrays - given two sorted integer arrays, find their median value as if they were merged into a single sorted sequence
- matrix search - determine if a target value exists in a matrix. each row of the matrix is sorted in non-decreasing order, and the first value of each row is greater than or equal to the last value of the previous row.
- local maxima - a local maxima is a value greater than both its immediate neighbors. return any local maxima in an array. you may assume that an element is always considered to be strictly greater than a neighbor that is outside the array.
- weighted random selection - given an array of items, each with a corresponding weight, implement a function that randomly selects an item from the array, where the probability of selecting any item is proportional to its weight.
** stack
- last in first out; push and pop, peek and isempty() - O(1) 
- example: nested or recursive function call management within operating systems or programming languages 
- valid parenthesis expression - given a string representing an expression of parentheses containing the characters '(', ')', '[', ']', '{', or '}', determine if the expression forms a valid sequence of parentheses. a sequence of parentheses is valid if every opening parenthesis has a corresponding closing parenthesis, and no closing parenthesis appears before its matching opening parenthesis.
- next largest number to the right - consider both left to right pass and right to left pass (later might be efficient than former for static information) 
- evaluate_expression - given a string representing a mathematical expression containing integers, parentheses, addition, and subtraction operators, evaluate and return the result of the expression.
- repeated removal of adj duplicates - given a string, continually perform the following operation: remove a pair of adjacent duplicates from the string. continue performing this operation until the string no longer contains pairs of adjacent duplicates. return the final string.
- queue - implement a queue using the stack data structure. enqueue, dequeue, peek. no other data structures to be used 
- maximums of sliding window - there's a sliding window of size k that slides through an integer array from left to right. create a new array that records the largest number found in each window as it slides through.
** heap
- a data structure that organizes elements based on priority, ensuring the highest-priority element is always at the top of the heap. this allows for efficient access to the highest-priority element at any time. types:
  - min-heap: prioritizes the smallest element by keeping it at the top of the heap
  - max-heap: prioritizes the largest element by keeping it at the top of the heap
- example: managing tasks in operating systems
- k most frequent strings: find the k most frequently occurring strings in an array, and return them sorted by frequency in descending order. if two strings have the same frequency, sort them in lexicographical order.
- combine sorted linked lists: given k singly linked lists, each sorted in ascending order, combine them into one sorted linked list
- median integer stream: design a data structure that supports adding integers from a data stream and retrieving the median of all elements received at any point.
  - example: streaming data. use min-heap and max-heap
    - filter out noise in hft
    - network monitoring and ddos mitigation (near 0 median alerts)
    - ad tech and user behaviour analytics 
- sort k-sorted array: given an integer array where each element is at most k positions away from its sorted position, sort the array in a non-decreasing order
  - examples:
    - network jitter and packet reordering
    - distributed log merging (timeseries databases)
    - high frequency trading (hft) market feeds
    - iot sensor telemetry aggregation
** intervals
- an interval consists of two values: a start point and an end point. it represents a continuous segment on the number line that includes all values between these two points. it is often used to represent a line, time period, or a continuous range of values.
  - closed intervals: both the start and end points are included in the interval
  - open intervals: the start and end points are not included in the interval
  - half-open intervals: either the start or the end point is included, while the other is not
  - overlapping intervals: two intervals overlap if they share at least one common value
  - example: scheduling systems
- merge overlapping intervals: merge an array of intervals so there are no overlapping intervals, and return the resultant merged intervals
- identify all overlaps: return an array of all overlaps between two arrays of intervals; each individual interval array is sorted by start value, and contains no overlapping intervals within itself
- largest overlap: given an array of intervals, determine the maximum number of intervals that overlap at any point. each interval is half-open, meaning it includes the start point but excludes the end point
** prefix sums
- example: cumulative earnings or expenses over time
- between range
- k-sum subarrays: find the number of subarrays in an integer array that sum to k
- product array without current element: given an array of integers, return an array res so that res[i] is equal to the product of all the elements of the input array except nums[i] itself
** trees
- example: file system is organized as hierarchial tree structure - efficient organization, navigation, and retrieval
- a tree is a hierarchical data structure composed of nodes, where each node connects to one or more child nodes
- each node in a tree contains the data it stores (val) and references to its child nodes
- the most common type of tree is a binary tree, in which each node connects to up to two children: a left child and a right child
- terminology
  - parent: a node with one or more children
  - child: a node that has a parent
  - subtree: a tree formed by a node and its descendants
  - path: a single, continuous sequence of nodes connected by edges
  - depth: the number of edges from the root to a given node
- attributes of a tree
  - root: the topmost node of the tree and the only node without a parent
  - intermediate node: a node with a parent node and at least one child
  - leaf: a node with no children
  - edge: the connection between two nodes. trees usually have directed edges, meaning the edges only point from parent to child
  - height: the length of the longest path from the root to a leaf
- traversals:
  - depth first search: preorder, inorder, postorder
|--------------------+-------------------+---------------------|
| preorder traversal | inorder traversal | postorder traversal |
|--------------------+-------------------+---------------------|
| process(node)      | dfs(node.left)    | dfs(node.left)      |
| dfs(node.left)     | process(node)     | dfs(node.right)     |
| dfs(node.right)    | dfs(node.right)   | process(node)       |
|--------------------+-------------------+---------------------|
  - breadth first search:  traverses the nodes of a tree level by level. it processes the nodes at the present level before moving on to nodes at the next depth level.
- invert binary tree: invert a binary tree and return its root. when a binary tree is inverted, it becomes the mirror image of itself.
- balanced bt validation: determine if a binary tree is height-balanced, meaning no node's left subtree and right subtree have a height difference greater than 1
- right most nodes: return an array containing the values of the rightmost nodes at each level of a binary tree
- widest level: return the width of the widest level in a binary tree, where the width of a level is defined as the distance between its leftmost and rightmost non-null nodes
- binary search tree (bst) validation: verify whether a binary tree is a valid binary search tree (bst). a bst is a binary tree where each node meets the following criteria:
  - a node's left subtree contains only nodes of lower values than the node's value
  - a node's right subtree contains only nodes of greater values than the node's value
- lowest common ancestor: return the lowest common ancestor (lca) of two nodes, p and q, in a binary tree. the lca is defined as the lowest node that has both p and q as descendants. a node can be considered an ancestor of itself.
- build bt from preorder and inorder traversal: construct a binary tree using arrays of values obtained after a preorder traversal and an inorder traversal of the tree
- maximum sum of continuous path: return the maximum sum of a continuous path in a binary tree. a path is defined by the following characteristics:
  - consists of a sequence of nodes that can begin and end at any node in the tree
  - each consecutive pair of nodes in the sequence is connected by an edge
  - the path must be a single continuous sequence of nodes that doesn't split into multiple paths
- symmetry: determine if a binary tree is vertically symmetric. that is, the left subtree of the root node is a mirror of the right subtree.  
- columns: given the root of a binary tree, return a list of arrays where each array represents a vertical column of the tree. nodes in the same column should be ordered from top to bottom. nodes in the same row and column should be ordered from left to right.
- kth_smallest: given the root of a binary search tree (bst) and an integer k, find the kth smallest node value  
- serialize and deserialize: write a function to serialize a binary tree into a string, and another function to deserialize that string back into the original binary tree structure
** tries
- tries, also known as prefix trees, are specialized tree-like data structures that efficiently store strings by taking advantage of shared prefixes.
- example: inter(/net, /face, /val), autocompletions, search strings, isword?
- design: operations insert, search, has_prefix?   
- insert and search with wildcards
- find all words in a board
** graphs
- a graph is a data structure composed of nodes (vertices) connected by edges. graphs are used to model relationships, where the edges define the relationships.
- terminology
  - adjacent node/neighbor: two nodes are adjacent if there’s an edge connecting them
  - degree: the number of edges connected to a node
  - path: a sequence of nodes connected by edges
- attributes
  - directed vs. undirected: in a directed graph, edges have a direction associated with them
  - weighted vs. unweighted: in a weighted graph, edges have a weight associated with them, such as distance or cost
  - cyclic vs. acyclic: a cyclic graph contains at least one cycle, which is a path that starts and ends at the same node
- other representations:
  - in an adjacency list, the neighbors of each node are stored as a list. adjacency lists can be implemented using a hash map, where the key represents the node, and its corresponding value represents the list of that node’s neighbors
  - in an adjacency matrix, the graph is represented as a 2d matrix where matrix[i][j] indicates an edge between nodes i and j
- traversals: dfs and bfs - it might also be necessary to keep track of visited nodes using a data structure such as a hash set, to ensure each node is only visited once
- example: social network 
- graph deep copy - given a reference to a node within an undirected graph, create a deep copy (clone) of the graph. the copied graph must be completely independent of the original one. this means you need to make new nodes for the copied graph instead of reusing any nodes from the original graph.
- count islands
- matrix infection
- bipartite graph validation
- longest increasing path
- shortest transformation seq
- merging communities
- prerequisites
- shortest paths
- connect the dots
** backtracking
- state space tree - also known as the decision tree, is a conceptual tree constructed by considering every possible decision that can be made at each point in a process


? monotonic window, sweep line approach, klee problem (shapes), birthday paradox, invariant law, attractor basin theory, floyd tortoise and hare, sentinel value pattern (-1)
** code blocks
# use this to run a specific program alone 
#+begin_src shell :results output
  python3 src/graphs_deep_copy.py
#+end_src

#+begin_src shell :results output
  python3 src/graphs_deep_copy.py
  python3 src/tries_find_words_board.py
  python3 src/tries_insert_search_wildcards.py
  python3 src/tries_design.py
  python3 src/bt_serialize_deserialize.py
  python3 src/bt_kth_smallest.py
  python3 src/bt_columns.py
  python3 src/bt_symmetry_check.py
  python3 src/bt_maxsum_continuous_path.py
  python3 src/bt_build_preorder_inorder_traversal.py
  python3 src/bt_lowest_common_ancestor.py
  python3 src/bt_binary_search_tree_validation.py
  python3 src/bt_widest_level.py
  python3 src/bt_right_most_nodes.py
  python3 src/bt_balance_verify.py
  python3 src/bt_invert.py
  python3 src/prefix_product_wo_ithelement.py
  python3 src/prefix_ksum_subarrays.py
  python3 src/prefix_sum_between_range.py
  python3 src/intervals_largest_overlap.py
  python3 src/intervals_identify_all_overlaps.py
  python3 src/intervals_merge_overlaps.py
  python3 src/heap_sort_ksorted_array.py
  python3 src/heap_median_integer_stream.py
  python3 src/heap_heapq.py
  python3 src/heap_combine_sorted_linked_lists.py
  python3 src/heap_k_most_freq.py
  python3 src/stack_maximums_sliding_window.py
  python3 src/stack_queue.py
  python3 src/stack_repeated_removal_adj_dplct.py
  python3 src/stack_eval_expression.py
  python3 src/stack_next_largest_right.py
  python3 src/stack_valid_parenthesis.py
  python3 src/binary_search_weighted_random_selection.py
  python3 src/binary_search_local_maxima.py
  python3 src/binary_search_matrix_search.py
  python3 src/binary_search_median_two_sorted_arrays.py
  python3 src/binary_search_rotated_sorted.py
  python3 src/binary_search_wood_cutting.py
  python3 src/binary_search_insertion_index.py
  python3 src/sliding_window_substring_uniform.py
  python3 src/sliding_window_substring_uniq.py
  python3 src/sliding_window_substring_anagram.py
  python3 src/fast_and_slow_happy_number.py
  python3 src/fast_and_slow_midpoint.py
  python3 src/fast_and_slow_linked_list_loop.py
  python3 src/linked_list_flatten_multilevel.py
  python3 src/linked_list_palindromic.py
  python3 src/linked_list_lru_cache.py
  python3 src/linked_list_intersection.py
  python3 src/linked_list_remove_kth.py
  python3 src/linked_list_reveral.py
  python3 src/geometric_seq_triplets.py 
  python3 src/longest_conseq_sequence.py
  python3 src/zero_striping_inplace.py
  python3 src/verify_sudoku_board.py
  python3 src/hashmap_pair_sum.py
  python3 src/lexicographical_sequence.py
  python3 src/shift_zeros_to_end.py
  python3 src/largest_container.py
  python3 src/palindrome_checker.py
  python3 src/triplet_sum.py
  python3 src/pair_sum.py
  ls -lha
#+end_src

** prompt tip
emacs. linux. debian. bash. python3. I will be running it as code block in emacs org mode file. I want to execute the given code in the script itself. include edge test cases. format test results in appropriate tables. add relevant description in results including header note, time and space complexity info, footer note. no need to use main function. rewrite fully, check thoroughly and send me the updated script.
