#!/usr/bin/env bb

(ns sync-harness
  (:require [babashka.fs :as fs]
            [clojure.string :as str])
  (:import [java.nio.file Files]))

;; Centralized Repository Paths
(def central-base "/home/rgroot/.local/share")
(def central-memory-dir "/home/rgroot/.local/share/agent-memory")
(def central-core-memory "/home/rgroot/.local/share/agent-memory/AGENTS_CORE.md")
(def central-tails-dir "/home/rgroot/.local/share/agent-memory/tails")
(def central-assembled-dir "/home/rgroot/.local/share/agent-memory/assembled")
(def central-skills "/home/rgroot/.local/share/skills")
(def central-prompts "/home/rgroot/.local/share/agent-prompts")

;; Harness Configuration Targets
(def harness-targets
  [{:name "Antigravity Gemini"
    :base "/home/rgroot/.gemini/config"
    :tail "gemini_tail.md"
    :assembled "/home/rgroot/.local/share/agent-memory/assembled/gemini.md"
    :links [{:sub "AGENTS.md" :target :assembled}
            {:sub "GEMINI.md" :target :assembled}
            {:sub "skills"    :target central-skills}
            {:sub "prompts"   :target central-prompts}]}

   {:name "Pi Agent"
    :base "/home/rgroot/.pi/agent"
    :tail "pi_tail.md"
    :assembled "/home/rgroot/.local/share/agent-memory/assembled/pi.md"
    :links [{:sub "AGENTS.md" :target :assembled}
            {:sub "skills"    :target central-skills}
            {:sub "prompts"   :target central-prompts}]}

   {:name "OpenCode Agent"
    :base "/home/rgroot/.config/opencode"
    :tail "opencode_tail.md"
    :assembled "/home/rgroot/.local/share/agent-memory/assembled/opencode.md"
    :links [{:sub "AGENTS.md" :target :assembled}
            {:sub "skills"    :target central-skills}
            {:sub "commands"  :target central-prompts}]}])

(defn symlink? [p]
  (Files/isSymbolicLink (fs/path (str p))))

(defn create-link! [link target]
  (fs/create-sym-link (str link) (str target)))

(defn ensure-central-exists! []
  (fs/create-dirs central-memory-dir)
  (fs/create-dirs central-tails-dir)
  (fs/create-dirs central-assembled-dir)
  (fs/create-dirs central-skills)
  (fs/create-dirs central-prompts)
  (when-not (fs/exists? central-core-memory)
    (spit central-core-memory "# Centralized Agent Memory\n")))

(defn assemble-memory-content [core-path tail-path]
  (let [core-text (if (fs/exists? core-path)
                    (str/trim (slurp (str core-path)))
                    "")
        tail-text (if (and tail-path (fs/exists? tail-path))
                    (str/trim (slurp (str tail-path)))
                    "")
        has-tail? (seq tail-text)
        header (str "<!-- AUTO-GENERATED BY harness-sync: DO NOT EDIT DIRECTLY -->\n"
                    "<!-- Source: " (fs/file-name core-path)
                    (if has-tail? (str " + tails/" (fs/file-name tail-path)) "")
                    " -->\n\n")]
    (str header
         core-text
         (if has-tail?
           (str "\n\n" tail-text "\n")
           "\n"))))

(defn assemble-memories! [dry-run?]
  (println "\n--- Assembling Agent Memory (Core + Tails) ---")
  (doseq [harness harness-targets]
    (let [tail-name (:tail harness)
          tail-file (when tail-name (str central-tails-dir "/" tail-name))
          target-assembled (:assembled harness)
          has-tail? (and tail-file (fs/exists? tail-file))
          content (assemble-memory-content central-core-memory tail-file)]
      (println (str "  [ASSEMBLE] " (:name harness) " -> " (fs/file-name target-assembled)
                    (if has-tail?
                      (str " (" (fs/file-name central-core-memory) " + " tail-name ")")
                      (str " (" (fs/file-name central-core-memory) " only)"))))
      (when-not dry-run?
        (spit target-assembled content)))))

(defn merge-skills-dir! [src-dir dst-dir dry-run?]
  (when (and (fs/exists? src-dir) (fs/directory? src-dir) (not (symlink? src-dir)))
    (doseq [f (fs/list-dir src-dir)]
      (let [item-name (fs/file-name f)
            target-item (str dst-dir "/" item-name)]
        (when-not (fs/exists? target-item)
          (println (str "    [MERGE] Moving skill '" item-name "' to central repository..."))
          (when-not dry-run?
            (fs/move f target-item {:replace-existing false})))))))

(defn process-link! [harness-spec link-spec dry-run?]
  (let [{:keys [sub target]} link-spec
        link-path (str (:base harness-spec) "/" sub)
        target-path (if (= target :assembled)
                      (:assembled harness-spec)
                      (str target))]

    ;; Ensure parent directory of link exists
    (let [parent-dir (str (fs/parent link-path))]
      (when-not (fs/exists? parent-dir)
        (when-not dry-run?
          (fs/create-dirs parent-dir))))

    (cond
      ;; Correct symlink already exists
      (and (symlink? link-path)
           (try (= (str (fs/canonicalize link-path)) (str (fs/canonicalize target-path)))
                (catch Exception _ false)))
      (println (str "  [OK] " sub " -> " target-path))

      ;; Incorrect symlink pointing elsewhere
      (symlink? link-path)
      (do
        (println (str "  [REPAIR SYMLINK] " sub " -> " target-path))
        (when-not dry-run?
          (fs/delete link-path)
          (create-link! link-path target-path)))

      ;; Real file or directory exists (needs migration to symlink)
      (fs/exists? link-path)
      (do
        (println (str "  [MIGRATE] Converting real " (if (fs/directory? link-path) "directory" "file") " '" sub "' to symlink..."))
        (when (and (fs/directory? link-path) (= sub "skills"))
          (merge-skills-dir! link-path target-path dry-run?))
        (when-not dry-run?
          (if (fs/directory? link-path)
            (fs/delete-tree link-path)
            (fs/delete link-path))
          (create-link! link-path target-path)))

      ;; Path missing: create symlink
      :else
      (do
        (println (str "  [CREATE SYMLINK] " sub " -> " target-path))
        (when-not dry-run?
          (create-link! link-path target-path))))))

(defn sync-harnesses! [{:keys [dry-run?]}]
  (println "=== Centralized Harness Symlink Manager ===")
  (println "Central Repository:" central-base)
  (println (str "Mode: " (if dry-run? "DRY RUN (No changes made)" "SYNC & LINK")))
  (println "-------------------------------------------")
  (ensure-central-exists!)
  (assemble-memories! dry-run?)

  (println "\n--- Synchronizing Harness Symlinks ---")
  (doseq [harness harness-targets]
    (println (str "\nChecking Harness: " (:name harness)))
    (doseq [link-spec (:links harness)]
      (process-link! harness link-spec dry-run?)))

  (println "\n-------------------------------------------")
  (println "Centralized Harness Synchronization Completed."))

(defn -main [& args]
  (let [dry-run? (some #{"--dry-run"} args)]
    (sync-harnesses! {:dry-run? dry-run?})))

(when (= *file* (System/getProperty "babashka.file"))
  (apply -main *command-line-args*))
