#!/usr/bin/env bb

(ns sync-harness
  (:require [babashka.fs :as fs]
            [clojure.string :as str])
  (:import [java.nio.file Files]))

;; Centralized Repository Paths
(def central-base "/home/rgroot/.local/share")
(def central-memory-dir "/home/rgroot/.local/share/agent-memory")
(def central-core-memory "/home/rgroot/.local/share/agent-memory/AGENTS_CORE.md")
(def central-tails-dir "/home/rgroot/.local/share/agent-memory/tails")
(def central-assembled-dir "/home/rgroot/.local/share/agent-memory/assembled")
(def central-skills "/home/rgroot/.local/share/skills")
(def central-prompts "/home/rgroot/.local/share/agent-prompts")

;; Anti-pollution and collision guardrails for Antigravity prompt bridges
(def agy-builtin-commands
  #{"goal" "schedule" "browser" "plan" "grill-me" "teamwork-preview" "learn" "boost"})

(def prompt-skill-collisions
  #{"find-bugs" "refactor" "review" "test" "plan"})

;; Harness Configuration Targets
(def harness-targets
  [{:name "Antigravity Gemini"
    :base "/home/rgroot/.gemini/config"
    :tail "gemini_tail.md"
    :assembled "/home/rgroot/.local/share/agent-memory/assembled/gemini.md"
    :links [{:sub "AGENTS.md" :target :assembled}
            {:sub "GEMINI.md" :target :assembled}
            {:sub "prompts"   :target central-prompts}]}

   {:name "Pi Agent"
    :base "/home/rgroot/.pi/agent"
    :tail "pi_tail.md"
    :assembled "/home/rgroot/.local/share/agent-memory/assembled/pi.md"
    :links [{:sub "AGENTS.md" :target :assembled}
            {:sub "skills"    :target central-skills}
            {:sub "prompts"   :target central-prompts}]}

   {:name "OpenCode Agent"
     :base "/home/rgroot/.config/opencode"
     :tail "opencode_tail.md"
     :assembled "/home/rgroot/.local/share/agent-memory/assembled/opencode.md"
     :links [{:sub "AGENTS.md" :target :assembled}
             {:sub "skills"    :target central-skills}
             {:sub "commands"  :target central-prompts}]}

   {:name "Emacs Gptel"
     :base "/home/rgroot/.emacs.d"
     :tail "emacs_tail.md"
     :assembled "/home/rgroot/.local/share/agent-memory/assembled/emacs.md"
     :links []}])

(defn symlink? [p]
  (Files/isSymbolicLink (fs/path (str p))))

(defn create-link! [link target]
  (fs/create-sym-link (str link) (str target)))

(defn ensure-central-exists! []
  (fs/create-dirs central-memory-dir)
  (fs/create-dirs central-tails-dir)
  (fs/create-dirs central-assembled-dir)
  (fs/create-dirs central-skills)
  (fs/create-dirs central-prompts)
  (when-not (fs/exists? central-core-memory)
    (spit central-core-memory "# Centralized Agent Memory\n")))

(defn assemble-memory-content [core-path tail-path]
  (let [core-text (if (fs/exists? core-path)
                    (str/trim (slurp (str core-path)))
                    "")
        tail-text (if (and tail-path (fs/exists? tail-path))
                    (str/trim (slurp (str tail-path)))
                    "")
        has-tail? (seq tail-text)
        header (str "<!-- AUTO-GENERATED BY harness-sync: DO NOT EDIT DIRECTLY -->\n"
                    "<!-- Source: " (fs/file-name core-path)
                    (if has-tail? (str " + tails/" (fs/file-name tail-path)) "")
                    " -->\n\n")]
    (str header
         core-text
         (if has-tail?
           (str "\n\n" tail-text "\n")
           "\n"))))

(defn assemble-memories! [dry-run?]
  (println "\n--- Assembling Agent Memory (Core + Tails) ---")
  (doseq [harness harness-targets]
    (let [tail-name (:tail harness)
          tail-file (when tail-name (str central-tails-dir "/" tail-name))
          target-assembled (:assembled harness)
          has-tail? (and tail-file (fs/exists? tail-file))
          content (assemble-memory-content central-core-memory tail-file)]
      (println (str "  [ASSEMBLE] " (:name harness) " -> " (fs/file-name target-assembled)
                    (if has-tail?
                      (str " (" (fs/file-name central-core-memory) " + " tail-name ")")
                      (str " (" (fs/file-name central-core-memory) " only)"))))
      (when-not dry-run?
        (spit target-assembled content)))))

(defn merge-skills-dir! [src-dir dst-dir dry-run?]
  (when (and (fs/exists? src-dir) (fs/directory? src-dir) (not (symlink? src-dir)))
    (doseq [f (fs/list-dir src-dir)]
      (let [item-name (fs/file-name f)
            target-item (str dst-dir "/" item-name)]
        (when-not (fs/exists? target-item)
          (println (str "    [MERGE] Moving skill '" item-name "' to central repository..."))
          (when-not dry-run?
            (fs/move f target-item {:replace-existing false})))))))

(defn parse-frontmatter
  "Extracts YAML frontmatter key-value pairs if present."
  [file-path]
  (try
    (let [lines (str/split-lines (slurp (str file-path)))]
      (if (and (seq lines) (= "---" (str/trim (first lines))))
        (let [fm-lines (take-while #(not= "---" (str/trim %)) (rest lines))]
          (into {}
                (keep (fn [line]
                        (when-let [[_ k v] (re-matches #"^([a-zA-Z0-9_-]+):\s*(.*)$" (str/trim line))]
                          [(keyword (str/lower-case k)) (str/trim v)])))
                fm-lines))
        {}))
    (catch Exception _ {})))

(defn eligible-prompt? [prompt-file central-skills-set]
  (let [p-name (str (fs/strip-ext (fs/file-name prompt-file)))
        fm (parse-frontmatter prompt-file)]
    (cond
      (contains? central-skills-set p-name)
      {:eligible? false :reason (str "collides with central skill '" p-name "'")}

      (contains? agy-builtin-commands p-name)
      {:eligible? false :reason (str "collides with Antigravity builtin '/" p-name "'")}

      (contains? prompt-skill-collisions p-name)
      {:eligible? false :reason "overlaps existing skill scope"}

      (empty? (:description fm))
      {:eligible? false :reason "lacks YAML frontmatter description"}

      :else
      {:eligible? true :name p-name :description (:description fm)})))

(defn sync-gemini-skills! [dry-run?]
  (println "\n--- Managing Antigravity Skills & Prompt Bridges ---")
  (let [gemini-skills-dir "/home/rgroot/.gemini/config/skills"
        central-skills-dirs (filter fs/directory? (fs/list-dir central-skills))
        central-skills-set (set (map #(str (fs/file-name %)) central-skills-dirs))
        expected-entries (atom #{})]

    ;; If gemini-skills-dir is a symlink pointing directly to central-skills, migrate to directory
    (when (symlink? gemini-skills-dir)
      (println "  [MIGRATE] Converting skills symlink to managed directory...")
      (when-not dry-run?
        (fs/delete gemini-skills-dir)
        (fs/create-dirs gemini-skills-dir)))

    (when-not (fs/exists? gemini-skills-dir)
      (when-not dry-run?
        (fs/create-dirs gemini-skills-dir)))

    ;; 1. Symlink central skills into gemini-skills-dir
    (doseq [skill-dir (sort-by #(str (fs/file-name %)) central-skills-dirs)]
      (let [s-name (str (fs/file-name skill-dir))
            link-path (str gemini-skills-dir "/" s-name)]
        (swap! expected-entries conj s-name)
        (cond
          (and (symlink? link-path)
               (try (= (str (fs/canonicalize link-path)) (str (fs/canonicalize skill-dir)))
                    (catch Exception _ false)))
          (println (str "  [OK SKILL] " s-name " -> " skill-dir))

          (symlink? link-path)
          (do
            (println (str "  [REPAIR SKILL SYMLINK] " s-name " -> " skill-dir))
            (when-not dry-run?
              (fs/delete link-path)
              (create-link! link-path skill-dir)))

          (fs/exists? link-path)
          (do
            (println (str "  [REPLACE EXISTING] " s-name " with symlink to central skill"))
            (when-not dry-run?
              (fs/delete-tree link-path)
              (create-link! link-path skill-dir)))

          :else
          (do
            (println (str "  [LINK SKILL] " s-name " -> " skill-dir))
            (when-not dry-run?
              (create-link! link-path skill-dir))))))

    ;; 2. Bridge eligible prompts into gemini-skills-dir
    (doseq [prompt-file (sort (filter #(str/ends-with? (str %) ".md") (fs/list-dir central-prompts)))]
      (let [p-name (str (fs/strip-ext (fs/file-name prompt-file)))
            check (eligible-prompt? prompt-file central-skills-set)]
        (if (:eligible? check)
          (let [bridge-dir (str gemini-skills-dir "/" p-name)
                skill-md (str bridge-dir "/SKILL.md")]
            (swap! expected-entries conj p-name)
            (when-not (fs/exists? bridge-dir)
              (println (str "  [CREATE BRIDGE DIR] " p-name))
              (when-not dry-run?
                (fs/create-dirs bridge-dir)))
            (cond
              (and (symlink? skill-md)
                   (try (= (str (fs/canonicalize skill-md)) (str (fs/canonicalize prompt-file)))
                        (catch Exception _ false)))
              (println (str "  [OK BRIDGE] /" p-name " -> " (fs/file-name prompt-file)))

              :else
              (do
                (println (str "  [BRIDGE PROMPT] /" p-name " -> " (fs/file-name prompt-file)))
                (when-not dry-run?
                  (when (fs/exists? skill-md) (fs/delete skill-md))
                  (create-link! skill-md prompt-file)))))
          (println (str "  [SKIP PROMPT] " p-name " (" (:reason check) ")")))))

    ;; 3. Prune stale entries
    (when (and (fs/exists? gemini-skills-dir) (fs/directory? gemini-skills-dir) (not (symlink? gemini-skills-dir)))
      (doseq [entry (fs/list-dir gemini-skills-dir)]
        (let [e-name (str (fs/file-name entry))]
          (when-not (contains? @expected-entries e-name)
            (println (str "  [PRUNE STALE] " e-name))
            (when-not dry-run?
              (if (fs/directory? entry)
                (fs/delete-tree entry)
                (fs/delete entry)))))))))

(defn process-link! [harness-spec link-spec dry-run?]
  (let [{:keys [sub target]} link-spec
        link-path (str (:base harness-spec) "/" sub)
        target-path (if (= target :assembled)
                      (:assembled harness-spec)
                      (str target))]

    ;; Ensure parent directory of link exists
    (let [parent-dir (str (fs/parent link-path))]
      (when-not (fs/exists? parent-dir)
        (when-not dry-run?
          (fs/create-dirs parent-dir))))

    (cond
      ;; Correct symlink already exists
      (and (symlink? link-path)
           (try (= (str (fs/canonicalize link-path)) (str (fs/canonicalize target-path)))
                (catch Exception _ false)))
      (println (str "  [OK] " sub " -> " target-path))

      ;; Incorrect symlink pointing elsewhere
      (symlink? link-path)
      (do
        (println (str "  [REPAIR SYMLINK] " sub " -> " target-path))
        (when-not dry-run?
          (fs/delete link-path)
          (create-link! link-path target-path)))

      ;; Real file or directory exists (needs migration to symlink)
      (fs/exists? link-path)
      (do
        (println (str "  [MIGRATE] Converting real " (if (fs/directory? link-path) "directory" "file") " '" sub "' to symlink..."))
        (when (and (fs/directory? link-path) (= sub "skills"))
          (merge-skills-dir! link-path target-path dry-run?))
        (when-not dry-run?
          (if (fs/directory? link-path)
            (fs/delete-tree link-path)
            (fs/delete link-path))
          (create-link! link-path target-path)))

      ;; Path missing: create symlink
      :else
      (do
        (println (str "  [CREATE SYMLINK] " sub " -> " target-path))
        (when-not dry-run?
          (create-link! link-path target-path))))))

(defn sync-harnesses! [{:keys [dry-run?]}]
  (println "=== Centralized Harness Symlink Manager ===")
  (println "Central Repository:" central-base)
  (println (str "Mode: " (if dry-run? "DRY RUN (No changes made)" "SYNC & LINK")))
  (println "-------------------------------------------")
  (ensure-central-exists!)
  (assemble-memories! dry-run?)

  (println "\n--- Synchronizing Harness Symlinks ---")
  (doseq [harness harness-targets]
    (println (str "\nChecking Harness: " (:name harness)))
    (doseq [link-spec (:links harness)]
      (process-link! harness link-spec dry-run?))
    (when (= (:name harness) "Antigravity Gemini")
      (sync-gemini-skills! dry-run?)))

  (println "\n-------------------------------------------")
  (println "Centralized Harness Synchronization Completed."))

(defn -main [& args]
  (let [dry-run? (some #{"--dry-run"} args)]
    (sync-harnesses! {:dry-run? dry-run?})))

(when (= *file* (System/getProperty "babashka.file"))
  (apply -main *command-line-args*))
